imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources: ~

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #java: /usr/bin/java
    filters:
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to:   "\.less$"
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        #unix_socket:	/var/mysql/mysql.sock
        types:
            point: PD\UserBundle\Wantlet\ORM\PointType
        mapping_types:
            point: string
    orm:
        dql:
            numeric_functions:
                              ACOS: DoctrineExtensions\Query\Mysql\Acos
                              SIN: DoctrineExtensions\Query\Mysql\Sin
                              RADIANS: DoctrineExtensions\Query\Mysql\Radians
                              COS: DoctrineExtensions\Query\Mysql\Cos
                              DISTANCE: PD\UserBundle\Wantlet\ORM\Distance
                              POINT_STR: PD\UserBundle\Wantlet\ORM\PointStr
                              RAND: PD\UserBundle\Wantlet\ORM\Rand
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_translator:
                type: annotation
                prefix: Gedmo\Translator\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # this one is optional and will default to the name set for the mapping
                is_bundle: false

# Swiftmailer Configuration
swiftmailer: ~

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: PD\UserBundle\Entity\User
    profile:
        form:
            type: pd_user_profile

services:
    cache:
        class: Doctrine\Common\Cache\ApcCache
    pd_user.profile.form.type:
       class: PD\UserBundle\Form\Type\ProfileFormType
       arguments: [%fos_user.model.user.class%]
       tags:
           - { name: form.type, alias: pd_user_profile }

fos_rest:
    view:
        view_response_listener: false
        failed_validation: HTTP_BAD_REQUEST
        default_engine: php
        formats:
            html: true
            json: true
            xml: true
            rss: false
    format_listener:
        default_priorities: ['html', 'json', xml, '*/*']
        fallback_format: json
        prefer_extension: true
    body_listener:
        decoders:
            json: fos_rest.decoder.json
            xml: fos_rest.decoder.xml
    routing_loader:
        default_format: json
    param_fetcher_listener: true

jms_serializer:
    metadata:
        cache: apc
        auto_detection: true
        directories:
            FOSUB:
                namespace_prefix: FOS\UserBundle
                path: %kernel.root_dir%/serializer/FOSUB

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            blameable: true
            loggable: true