<?php
namespace PD\SiteBundle\Entity\Repositories;

use PD\SiteBundle\Entity\SearchCriteria;
use PD\UserBundle\Wantlet\ORM\Point;

use Doctrine\ORM\QueryBuilder;

/**
 * DishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogRepository extends BaseRepository
{
    /**
     * @return Cookisto\DishBundle\Entity\BaseDish
     */
    public function findDogs(SearchCriteria $criteria) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('d');
        $qb->from($this->_entityName, 'd');

        if ($criteria->getPoint() != null) {
            $qb->join('d.user', 'du');
            $qb->andWhere('DISTANCE(du.point, POINT_STR(:umaxpoint) ) <= :umaxdistance');
            $qb->setParameter('umaxpoint', $criteria->getPoint());
            $qb->setParameter('umaxdistance', '100');
        }
        if($criteria->getBreed() != null) {
            $qb->join('d.breed', 'br');
            $qb->andWhere('br.id = :breed');
            $qb->setParameter('breed', $criteria->getBreed()->getId());
        }
        if($criteria->getGender() != null) {
            $qb->andWhere('d.gender = :gender');
            $qb->setParameter('gender', $criteria->getGender());
        }

        return $this->getResult($qb, false);
    }
}
